data = [
    {
        'name': 'Virat Kohli', 
        'follower_count': 270, 
        'description': 'Indian international cricketer', 
        'country': 'India'
    },
    {
        'name': 'Rohit Sharma', 
        'follower_count': 40,
        'description': 'Indian international cricketer',
        'country': 'India'
    },
    {
        'name': 'MS Dhoni', 
        'follower_count': 45,
        'description': 'Former Indian international cricketer', 
        'country': 'India'
    },
    {
        'name': 'Hardik Pandya',
        'follower_count': 35,
        'description': 'Indian international cricketer', 
        'country': 'India'
    },
    {'name': 'KL Rahul', 'follower_count': 18, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Jasprit Bumrah', 'follower_count': 15, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Shubman Gill', 'follower_count': 20, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Ravindra Jadeja', 'follower_count': 12, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Suryakumar Yadav', 'follower_count': 14, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Rishabh Pant', 'follower_count': 16, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Yuzvendra Chahal', 'follower_count': 11, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Kuldeep Yadav', 'follower_count': 8, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Mohammed Shami', 'follower_count': 9, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Ishan Kishan', 'follower_count': 13, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Sanju Samson', 'follower_count': 11, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Shreyas Iyer', 'follower_count': 12, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Axar Patel', 'follower_count': 7, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Bhuvneshwar Kumar', 'follower_count': 6, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Deepak Chahar', 'follower_count': 7, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Prithvi Shaw', 'follower_count': 9, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Washington Sundar', 'follower_count': 5, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Rahul Tripathi', 'follower_count': 4, 'description': 'Indian cricketer', 'country': 'India'},
    {'name': 'Nitish Rana', 'follower_count': 4, 'description': 'Indian cricketer', 'country': 'India'},
    {'name': 'Mayank Agarwal', 'follower_count': 6, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Chennai Super Kings', 'follower_count': 15, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Mumbai Indians', 'follower_count': 13, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Royal Challengers Bengaluru', 'follower_count': 14, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Kolkata Knight Riders', 'follower_count': 12, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Sunrisers Hyderabad', 'follower_count': 9, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Delhi Capitals', 'follower_count': 10, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Rajasthan Royals', 'follower_count': 9, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Punjab Kings', 'follower_count': 8, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Lucknow Super Giants', 'follower_count': 7, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Gujarat Titans', 'follower_count': 8, 'description': 'IPL cricket team', 'country': 'India'},
    {'name': 'Virender Sehwag', 'follower_count': 7, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Sourav Ganguly', 'follower_count': 6, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Anil Kumble', 'follower_count': 5, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Harbhajan Singh', 'follower_count': 6, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Zaheer Khan', 'follower_count': 4, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'VVS Laxman', 'follower_count': 3, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Yuvraj Singh', 'follower_count': 12, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Irfan Pathan', 'follower_count': 5, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Mohammad Kaif', 'follower_count': 3, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Gautam Gambhir', 'follower_count': 6, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Robin Uthappa', 'follower_count': 4, 'description': 'Former Indian cricketer', 'country': 'India'},
    {'name': 'Dinesh Karthik', 'follower_count': 6, 'description': 'Indian cricketer', 'country': 'India'},
    {'name': 'Wriddhiman Saha', 'follower_count': 2, 'description': 'Indian cricketer', 'country': 'India'},
    {'name': 'Ajinkya Rahane', 'follower_count': 5, 'description': 'Indian international cricketer', 'country': 'India'},
    {'name': 'Cheteshwar Pujara', 'follower_count': 3, 'description': 'Indian international cricketer', 'country': 'India'}
]
